language: python
python:
- '3.6'
deploy:
  provider: pypi
  user: andreroggeri
  skip_upload_docs: true
  password:
    secure: FfLE/+ti1dqvGLZKes6GrDnYSZUYSLjnM1rybX2W/aPcd8/igObJyJva6ixmxBQz6spiDjPD0GVjwhkxEdl8m6sN2/Jq6aT583qUmg5ipGc7FHzE8DM/2l2s7J7kabT7JHV8Bs30AIXcdMKGHfwl5JPKgGjWIaBZCeDBOP7aXWYPlPLxKhl8fQ7ucPcK1QE0cvrJx+q8s7a2na7S396oDxfoOK5BOjKGoTtfl4e0yBLsuKDMlzVjpjGVim0N7MMumSbunSMqKGliLu6ti8P2eofPBFHnjVTQOdrGiYL20BXZxNUYU4flABAUij0QHAWs0ADwLXFn4DNFwLa8e5VxReRYJIlSap3utKbi7pRj2t1BOlas0HZm4sYUaAgsL3uNZrEjbBaO9JRNp57DLXEa0Xl9QhWpldyflqgnCDLH8+0ogKvP+IByNXBM7/4FjdcVizG5Z29FsSRpzGCxV2FI+6mVyL8M8Hw3zwqgMvSYsClQ+EjfwXjgwyCEDJ1cEwiI+gpufQM1skjxDMzUUOqUv4R3gQ4CTboUu2yKJZZEABYfbO2EVgWaXIvdcAijV6imR93+mLiMk15ubuPSZALrhVRN26K+xuiHpDdiXz9aK4FQXZwqxMkbKG9W65oJ02dn+nb/QNwmFtMwOw6KEDZKxJrKvyfcSzw88hzjAyCR/6Q=