language: python
python:
- '3.6'
script:
- echo "ok"
deploy:
  provider: pypi
  user: andreroggeri
  skip_upload_docs: true
  password:
    secure: K30Qc4gYVwttnZSEUmDPiTnEPpBL+MvceccWxeUYcdfdnxSo8iSQFs8v0uRHbchUbLJMKepsbnzFLH0LIbtKTRFiJMHx1/DLgobTqvm9CZ6d/iGb1UjKoQ5BH6FChU2YSTGuMNJp9awJqaiIcEJLbJEnbAGz2Hh/hiG/QbrxIeQZ80kaO8KI0WWr+tE4vqEAqheUfQbBuJDczuWhZHNTxVoHKod7uNw6ko0eOxsBDOTsgnPCG4MXzKYSuMlVX2rLtySCEhTV8LnAIonpH80HigfbMUSOxUPf+Ax5BCZtelPjh7IaSZ0H73TRvXsqc7JHq1eW3VkHtl5+6vlwCUUX5PQumCPShkhpS3MpVB4JGsemtKzG5HXnfnkljmbyV2IcGZFv2+JfQXhU7xQIROVmUnKlJAfkAl5wAlyg22RRZQdz/szZxEchDVkIR2giXsrnKi7DLgRtrknOIS+XbBAJTlLbDfvSMtsVPj9o8N8lDBv6pRprIufDeG2421ftOLlCKPo7CSE0Us7GAPZyx/YEPSsLrRv48L4i4mZ9q/0TDtWHZCpwEbAV2rn4LK+KohGxr/2lSeIhvd0pwB3N6vr2VbQhwYlGd/4X7nXwFGxwZywIQXafJUv/Cb95Dp6FeEe5WLZjA8eDNVVhIp1gTBQIiH6R8zndaomXRTJifmnOvq4=
  on:
    all_branches: true
