language: python
python:
- '3.6'
script:
- echo "ok"
deploy:
  provider: pypi
  user: andreroggeri
  skip_upload_docs: true
  password:
    secure: oS5XObmMC7G9ZQ4gfPs4xS2+HF6Yj3TyxbH0CnTtwYTfvYikTMFAL7ZegtnO3GQlVz7h7e3TSWX8ore2xu1qNDv6pRbkTl9SpaRA3TUg8utKzBkIhSp/E5EEGUJERws61rovCv52+9fuxrt2RbJXLtZ1y0P5SVXRO+WpkzZd5iZUBNKSbE4Go9PLkYJWqatR8V0oepXL2cL3Z5aWz1/5wIDO8as+57RdT4rMUSB17rKim2Nt1jwIreCyIjpZVgNb33UyEaOeM1B17wYzQLKaXs+gcZdb+E/C7U8duaDs8nDOgN8QqodM5fcqh8DlIvcDPJTTj1gY42t5Yz5hL1QMWYmf8qXMue7ZQXa8n9A3jJhVeBH260RhlwOStoiRph+9YUQU+6vhey67ohSly1PbLLzoKQ43k74lkwJDV1FBWvohmU9wx/W+VTZgAXc824v2Q5SXjHkTkBQY9uleErmRi3hkWi0zR4LMHq1O8u9x9cZ76A0kR0qSPyvl0jbr9+uk9LnWN7pqQJzG7dBo1mVsYnAf8UHKqstGt5E/d88gIGGNQOErDeWwAaKaemMIHusM/VsY7EKWaG1UrsOFEpupbAIog3yFkecIrGnZHayhiprQBhJiUB/czSPG7J53tCCZBvwUVV7VWkdie/z+VzgckxNOg6cPIabP/PFZq6An3uw=
  on:
    all_branches: true
